### ISSUE TITLE
PCI1: force mSata config option.

### ISSUE THREAD

**Issue by Anulap** [CZ-NIC/turris-os#30]
So there are some users like myself who experience problems with some mSata SSDs not being detected by Omnia. It is probably caused by rather lax standards adoption by manufacturers (for example some Kingston SSDs), however they work on compatible PCs and Omnia with external enclosure. 
A temporary, but fair solution would be to implement corresponding config option, so Omnia can be forced to switch PCI1 into mSata mode.

**Comment by tmshlvck** [comment]
Hi!

Well the problem is that there are two things that are dependent on MSATAIND signal (see schematic https://www.turris.cz/doc/_media/rtrom01-schema.pdf):

1) RX pair crossover and coupling capacitor value (which is hard-wired by passing the signal to U12 and U13 ICs)
2) SERDES multiplexer configuration (which is U-Boot job and can be hacked)

We can theoretically override the value on the signal by setting appropriate MCU pin to desired value to pull up/down the value (by default there is 4k7 pull-up resistor setting the un-connected pin to PCIe mode). The problem is that if the card is shorted to either 3V3 or GND we can burn the MCU.

I think that if you really need to use mSATA SSD that does not conform the specification I would suggest to do a simple HW mod on the SSD PCB - it should be quite simple to cut off the mSATA indication pin (43) and hack a bridge to GND there.

Anyway I'll try to suggest to have complete SW switching mechanism in next Omnia revision - but I am not sure whether we have spare MCU GPIO...

Sorry for bad news!
Tomas
