### ISSUE TITLE
outdated OpenWRT packages

### ISSUE THREAD

**Issue by chpio** [CZ-NIC/turris-os#76]
the *feeds.conf.default* references some really old commits, eg: https://github.com/openwrt-routing/packages/commit/a4eae82c155079a4372e4b910ec733f77288b717

Is this intended, and the *feeds.conf.default* is just irrelevant? Any way... the *cjdns* package is massively outdated ([v17.3 in *omnia_routing* repository](https://repo.turris.cz/omnia/packages//routing), [the current version is v20.1](https://github.com/openwrt-routing/packages/commit/733e935f04fc6fa7a0e45fddca140cb9518995fe)).

At least you should remove all outdated repositories.

**Comment by ja-pa** [comment]
Hi,
yes it's intended  because right now, we can't update it without breaking too many stuff. Some packages are not so old, because we are patching them see  https://gitlab.labs.nic.cz/turris/openwrt/tree/test/patches.
With TurrisOS 4.0 we will be based on latest Openwrt and we'll follow upstream much closely so we'll not end in situation like this anymore.

**Comment by chpio** [comment]
Thank you.
